SUB_TYPE_DICT = {
    'BTCUSDT': 'PoW', 'ETHUSDT': 'Layer-1', 'BCHUSDT': 'PoW', 'XRPUSDT': 'Payment', 'EOSUSDT': 'Layer-1',
    'LTCUSDT': 'PoW', 'TRXUSDT': 'Layer-1', 'ETCUSDT': 'Layer-1', 'LINKUSDT': 'Oracle', 'XLMUSDT': 'Layer-2',
    'ADAUSDT': 'Layer-1', 'XMRUSDT': 'Privacy', 'DASHUSDT': 'Payment', 'ZECUSDT': 'Privacy', 'XTZUSDT': 'Layer-1',
    'BNBUSDT': 'Layer-1', 'ATOMUSDT': 'Layer-1', 'ONTUSDT': 'Layer-1', 'IOTAUSDT': 'Layer-1',
    'BATUSDT': 'Infrastructure', 'VETUSDT': 'Layer-1', 'NEOUSDT': 'Layer-1', 'QTUMUSDT': 'Layer-1',
    'IOSTUSDT': 'Layer-1', 'THETAUSDT': 'NFT', 'ALGOUSDT': 'Layer-1', 'ZILUSDT': 'Layer-1', 'KNCUSDT': 'DeFi',
    'ZRXUSDT': 'DEX', 'COMPUSDT': 'DeFi', 'OMGUSDT': 'Layer-2', 'DOGEUSDT': 'Meme', 'SXPUSDT': 'Payment',
    'KAVAUSDT': 'Layer-1', 'BANDUSDT': 'Oracle', 'RLCUSDT': 'Oracle', 'WAVESUSDT': 'Layer-1', 'MKRUSDT': 'DeFi',
    'SNXUSDT': 'DEX', 'DOTUSDT': 'Layer-1', 'DEFIUSDT': 'Index', 'YFIUSDT': 'DeFi', 'BALUSDT': 'DEX', 'CRVUSDT': 'DeFi',
    'TRBUSDT': 'Oracle', 'RUNEUSDT': 'DEX', 'SUSHIUSDT': 'DEX', 'SRMUSDT': 'DEX', 'EGLDUSDT': 'Layer-1',
    'SOLUSDT': 'Layer-1', 'ICXUSDT': 'Layer-1', 'STORJUSDT': 'Storage', 'BLZUSDT': 'Storage', 'UNIUSDT': 'DEX',
    'AVAXUSDT': 'Layer-1', 'FTMUSDT': 'Layer-1', 'HNTUSDT': 'Infrastructure', 'ENJUSDT': 'NFT', 'FLMUSDT': 'DeFi',
    'TOMOUSDT': 'Layer-1', 'RENUSDT': 'DeFi', 'KSMUSDT': 'Layer-1', 'NEARUSDT': 'Layer-2', 'AAVEUSDT': 'DeFi',
    'FILUSDT': 'Storage', 'RSRUSDT': 'DeFi', 'LRCUSDT': 'DEX', 'MATICUSDT': 'Layer-2', 'OCEANUSDT': 'AI',
    'CVCUSDT': 'Infrastructure', 'BELUSDT': 'DeFi', 'CTKUSDT': 'Infrastructure', 'AXSUSDT': 'Metaverse',
    'ALPHAUSDT': 'DeFi', 'ZENUSDT': 'Privacy', 'SKLUSDT': 'Layer-2', 'GRTUSDT': 'Oracle', '1INCHUSDT': 'DEX',
    'CHZUSDT': 'Layer-1', 'SANDUSDT': 'Metaverse', 'ANKRUSDT': 'DeFi', 'BTSUSDT': 'DEX', 'LITUSDT': 'Privacy',
    'UNFIUSDT': 'DeFi', 'REEFUSDT': 'DeFi', 'RVNUSDT': 'PoW', 'SFPUSDT': 'Infrastructure', 'XEMUSDT': 'Layer-1',
    'BTCSTUSDT': 'DEFI', 'COTIUSDT': 'Payment', 'CHRUSDT': 'Layer-2', 'MANAUSDT': 'Metaverse', 'ALICEUSDT': 'Metaverse',
    'HBARUSDT': 'Layer-1', 'ONEUSDT': 'Layer-2', 'LINAUSDT': 'DeFi', 'STMXUSDT': 'Payment',
    'DENTUSDT': 'Infrastructure', 'CELRUSDT': 'Layer-2', 'HOTUSDT': 'Storage', 'MTLUSDT': 'Infrastructure',
    'OGNUSDT': 'NFT', 'NKNUSDT': 'Infrastructure', 'SCUSDT': 'Storage', 'DGBUSDT': 'Payment', '1000SHIBUSDT': 'Meme',
    'BAKEUSDT': 'DeFi', 'GTCUSDT': 'Infrastructure', 'BTCDOMUSDT': 'Index', 'IOTXUSDT': 'Layer-1', 'AUDIOUSDT': 'NFT',
    'RAYUSDT': 'DEX', 'C98USDT': 'DeFi', 'MASKUSDT': 'Privacy', 'ATAUSDT': 'Privacy', 'DYDXUSDT': 'DEX',
    '1000XECUSDT': 'Payment', 'GALAUSDT': 'Metaverse', 'CELOUSDT': 'Layer-1', 'ARUSDT': 'Storage',
    'KLAYUSDT': 'Layer-1', 'ARPAUSDT': 'DeFi', 'CTSIUSDT': 'Layer-2', 'LPTUSDT': 'Infrastructure',
    'ENSUSDT': 'Infrastructure', 'PEOPLEUSDT': 'DAO', 'ANTUSDT': 'DAO', 'ROSEUSDT': 'Layer-1', 'DUSKUSDT': 'Privacy',
    'FLOWUSDT': 'Layer-1', 'IMXUSDT': 'Layer-2', 'API3USDT': 'Infrastructure', 'GMTUSDT': 'NFT', 'APEUSDT': 'NFT',
    'WOOUSDT': 'DeFi', 'FTTUSDT': 'CEX', 'JASMYUSDT': 'Infrastructure', 'DARUSDT': 'NFT', 'GALUSDT': 'Infrastructure',
    'OPUSDT': 'Layer-2', 'INJUSDT': 'DeFi', 'STGUSDT': 'others', 'FOOTBALLUSDT': 'Index', 'SPELLUSDT': 'DeFi',
    '1000LUNCUSDT': 'Layer-1', 'LUNA2USDT': 'Layer-1', 'LDOUSDT': 'Layer-2', 'CVXUSDT': 'DeFi', 'ICPUSDT': 'Layer-1',
    'APTUSDT': 'Layer-1', 'QNTUSDT': 'Infrastructure', 'BLUEBIRDUSDT': 'Index', 'FETUSDT': 'AI', 'FXSUSDT': 'DeFi',
    'HOOKUSDT': 'Infrastructure', 'MAGICUSDT': 'Metaverse', 'TUSDT': 'Bitcoin Eco', 'RNDRUSDT': 'Infrastructure',
    'HIGHUSDT': 'Metaverse', 'MINAUSDT': 'Privacy', 'ASTRUSDT': 'Infrastructure', 'AGIXUSDT': 'AI',
    'PHBUSDT': 'Infrastructure', 'GMXUSDT': 'DeFi', 'CFXUSDT': 'Layer-1', 'STXUSDT': 'Layer-1',
    'COCOSUSDT': 'Metaverse', 'BNXUSDT': 'NFT', 'ACHUSDT': 'Payment', 'SSVUSDT': 'Infrastructure', 'CKBUSDT': 'PoW',
    'PERPUSDT': 'DeFi', 'TRUUSDT': 'DeFi', 'LQTYUSDT': 'DeFi', 'USDCUSDT': 'DeFi', 'IDUSDT': 'Infrastructure',
    'ARBUSDT': 'Layer-2', 'JOEUSDT': 'DEX', 'TLMUSDT': 'Metaverse', 'AMBUSDT': 'Layer-1', 'LEVERUSDT': 'DeFi',
    'RDNTUSDT': 'DeFi', 'HFTUSDT': 'DeFi', 'XVSUSDT': 'DeFi', 'ETHBTC': 'Cross Pair', 'BLURUSDT': 'NFT',
    'EDUUSDT': 'Metaverse', 'IDEXUSDT': 'DeFi', 'SUIUSDT': 'Layer-1', '1000PEPEUSDT': 'Meme', '1000FLOKIUSDT': 'Meme',
    'UMAUSDT': 'DeFi', 'RADUSDT': 'DeFi', 'KEYUSDT': 'Infrastructure', 'COMBOUSDT': 'Metaverse', 'NMRUSDT': 'DeFi',
    'MAVUSDT': 'DeFi', 'MDTUSDT': 'Infrastructure', 'XVGUSDT': 'PoW', 'WLDUSDT': 'AI', 'PENDLEUSDT': 'DeFi',
    'ARKMUSDT': 'AI', 'AGLDUSDT': 'NFT', 'YGGUSDT': 'Metaverse', 'DODOXUSDT': 'DeFi', 'BNTUSDT': 'DeFi',
    'OXTUSDT': 'Infrastructure', 'SEIUSDT': 'Layer-1', 'CYBERUSDT': 'Infrastructure', 'HIFIUSDT': 'DeFi',
    'ARKUSDT': 'Infrastructure', 'FRONTUSDT': 'DeFi', 'GLMRUSDT': 'Layer-2', 'BICOUSDT': 'Infrastructure',
    'STRAXUSDT': 'Layer-2', 'LOOMUSDT': 'Infrastructure', 'BIGTIMEUSDT': 'Metaverse', 'BONDUSDT': 'DeFi',
    'ORBSUSDT': 'Infrastructure', 'STPTUSDT': 'DeFi', 'WAXPUSDT': 'NFT', 'BSVUSDT': 'PoW', 'RIFUSDT': 'Bitcoin Eco',
    'POLYXUSDT': 'Layer-1', 'GASUSDT': 'DeFi', 'POWRUSDT': 'Layer-2', 'SLPUSDT': 'Metaverse', 'TIAUSDT': 'Layer-1',
    'SNTUSDT': 'DeFi', 'CAKEUSDT': 'DEX', 'MEMEUSDT': 'Meme', 'TWTUSDT': 'Infrastructure', 'TOKENUSDT': 'DeFi',
    'ORDIUSDT': 'Bitcoin Eco', 'STEEMUSDT': 'DeFi', 'BADGERUSDT': 'Bitcoin Eco', 'ILVUSDT': 'Metaverse',
    'NTRNUSDT': 'Layer-1', 'MBLUSDT': 'Metaverse', 'KASUSDT': 'PoW', 'BEAMXUSDT': 'Infrastructure',
    '1000BONKUSDT': 'Meme', 'PYTHUSDT': 'Oracle', 'SUPERUSDT': 'NFT', 'USTCUSDT': 'DeFi', 'ONGUSDT': 'Layer-1',
    'ETHWUSDT': 'PoW', 'JTOUSDT': 'DeFi', '1000SATSUSDT': 'Meme', 'AUCTIONUSDT': 'DeFi', '1000RATSUSDT': 'Meme',
    'ACEUSDT': 'Metaverse', 'MOVRUSDT': 'Layer-1', 'NFPUSDT': 'AI', 'BTCUSDT_240628': 'others',
    'ETHUSDT_240628': 'others', 'BTCUSDC': 'USDC', 'ETHUSDC': 'USDC', 'BNBUSDC': 'USDC', 'SOLUSDC': 'USDC',
    'XRPUSDC': 'USDC', 'AIUSDT': 'others', 'XAIUSDT': 'others', 'DOGEUSDC': 'USDC', 'WIFUSDT': 'Meme',
    'MANTAUSDT': 'Layer-2', 'ONDOUSDT': 'Layer-1', 'LSKUSDT': 'Layer-1', 'ALTUSDT': 'Layer-1', 'JUPUSDT': 'Dex',
    'ZETAUSDT': 'Infrastructure', 'RONINUSDT': 'Layer-1', 'DYMUSDT': 'Infrastructure', 'SUIUSDC': 'USDC',
    'OMUSDT': 'DeFi', 'LINKUSDC': 'USDC', 'PIXELUSDT': 'Metaverse', 'STRKUSDT': 'Infrastructure', 'MAVIAUSDT': 'others',
    'ORDIUSDC': 'USDC', 'GLMUSDT': 'others', 'PORTALUSDT': 'Metaverse', 'TONUSDT': 'others',
    'AXLUSDT': 'Infrastructure', 'MYROUSDT': 'MEME', '1000PEPEUSDC': 'USDC', 'METISUSDT': 'Layer-2',
    'AEVOUSDT': 'others', 'WLDUSDC': 'USDC', 'VANRYUSDT': 'others', 'BOMEUSDT': 'others', 'ETHFIUSDT': 'DeFi',
    'AVAXUSDC': 'USDC', '1000SHIBUSDC': 'USDC', 'BTCUSDT_240927': 'others', 'ETHUSDT_240927': 'others',
    'ENAUSDT': 'others', 'WUSDT': 'others', 'WIFUSDC': 'USDC', 'BCHUSDC': 'USDC', 'TNSRUSDT': 'others',
    'SAGAUSDT': 'others', 'LTCUSDC': 'others', 'NEARUSDC': 'others', 'TAOUSDT': 'others'}
