import asyncio

from quant_trade_go.order_handler import OrderHandlerV1


async def main(oh):
    tasks = [oh.place_order(order) for order in orders]
    list_res = await asyncio.gather(*tasks)
    return list_res


if __name__ == '__main__':
    orders = [
        {'symbol': '1000LUNCUSDT',
         'type': 'MARKET',
         'quantity': '20',
         'side': 'BUY',
         'recvWindow': '5000',
         'newClientOrderId': 'test0'},
        # {'symbol': 'API3USDT',
        #  'type': 'MARKET',
        #  'quantity': '10.4',
        #  'side': 'BUY',
        #  'recvWindow': '5000'},
        # {'symbol': 'ARPAUSDT',
        #  'type': 'MARKET',
        #  'quantity': '345.0',
        #  'side': 'BUY',
        #  'recvWindow': '5000'},
        # {'symbol': 'CTSIUSDT',
        #  'type': 'MARKET',
        #  'quantity': '108.0',
        #  'side': 'BUY',
        #  'recvWindow': '5000'},
        # {'symbol': 'MAGICUSDT',
        #  'type': 'MARKET',
        #  'quantity': '39.0',
        #  'side': 'BUY',
        #  'recvWindow': '5000'},
        # {'symbol': 'MASKUSDT',
        #  'type': 'MARKET',
        #  'quantity': '6.0',
        #  'side': 'BUY',
        #  'recvWindow': '5000'},
        # {'symbol': 'OXTUSDT',
        #  'type': 'MARKET',
        #  'quantity': '163.0',
        #  'side': 'BUY',
        #  'recvWindow': '5000'},
        # {'symbol': 'RDNTUSDT',
        #  'type': 'MARKET',
        #  'quantity': '286.0',
        #  'side': 'BUY',
        #  'recvWindow': '5000'},
        # {'symbol': 'SNXUSDT',
        #  'type': 'MARKET',
        #  'quantity': '7.8',
        #  'side': 'BUY',
        #  'recvWindow': '5000'},
        # {'symbol': 'TWTUSDT',
        #  'type': 'MARKET',
        #  'quantity': '14.0',
        #  'side': 'BUY',
        #  'recvWindow': '5000'},
        # {'symbol': 'UMAUSDT',
        #  'type': 'MARKET',
        #  'quantity': '6.0',
        #  'side': 'BUY',
        #  'recvWindow': '5000'},
        # {'symbol': 'YFIUSDT',
        #  'type': 'MARKET',
        #  'quantity': '0.002',
        #  'side': 'BUY',
        #  'recvWindow': '5000'},
        # {'symbol': '1000BONKUSDT',
        #  'type': 'MARKET',
        #  'quantity': '682.0',
        #  'side': 'SELL',
        #  'recvWindow': '5000'},
        # {'symbol': '1MBABYDOGEUSDT',
        #  'type': 'MARKET',
        #  'quantity': '5709.0',
        #  'side': 'SELL',
        #  'recvWindow': '5000'},
        # {'symbol': 'BIGTIMEUSDT',
        #  'type': 'MARKET',
        #  'quantity': '135.0',
        #  'side': 'SELL',
        #  'recvWindow': '5000'},
        # {'symbol': 'BLZUSDT',
        #  'type': 'MARKET',
        #  'quantity': '287.0',
        #  'side': 'SELL',
        #  'recvWindow': '5000'},
        # {'symbol': 'HBARUSDT',
        #  'type': 'MARKET',
        #  'quantity': '72.0',
        #  'side': 'SELL',
        #  'recvWindow': '5000'},
        # {'symbol': 'MOODENGUSDT',
        #  'type': 'MARKET',
        #  'quantity': '78.0',
        #  'side': 'SELL',
        #  'recvWindow': '5000'},
        # {'symbol': 'POPCATUSDT',
        #  'type': 'MARKET',
        #  'quantity': '26.0',
        #  'side': 'SELL',
        #  'recvWindow': '5000'},
        # {'symbol': 'WLDUSDT',
        #  'type': 'MARKET',
        #  'quantity': '9.0',
        #  'side': 'SELL',
        #  'recvWindow': '5000'},
        # {'symbol': 'XTZUSDT',
        #  'type': 'MARKET',
        #  'quantity': '16.1',
        #  'side': 'SELL',
        #  'recvWindow': '5000'},
        # {'symbol': 'ZENUSDT',
        #  'type': 'MARKET',
        #  'quantity': '1.1',
        #  'side': 'SELL',
        #  'recvWindow': '5000'}
    ]

    order_handler = OrderHandlerV1(True)

    loop = asyncio.get_event_loop()
    list_res = loop.run_until_complete(main(order_handler))
    loop.close()
    print(list_res)
